// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAxsfjMA5Fj-n3JHsVpxpXhiExx4j6qNQ',
    appId: '1:209148374373:web:3377f3fc03f879aa97458c',
    messagingSenderId: '209148374373',
    projectId: 'socailmediaapp-f2758',
    authDomain: 'socailmediaapp-f2758.firebaseapp.com',
    storageBucket: 'socailmediaapp-f2758.firebasestorage.app',
    measurementId: 'G-YXBHTZC6B7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDASVSBemeARhEJzLJUd3fq3fVLpnuTULg',
    appId: '1:209148374373:android:97489b360b52163297458c',
    messagingSenderId: '209148374373',
    projectId: 'socailmediaapp-f2758',
    storageBucket: 'socailmediaapp-f2758.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5QaiFJdBxCrvQbyYA823znZZj68JPmYI',
    appId: '1:209148374373:ios:6e117850347ce93b97458c',
    messagingSenderId: '209148374373',
    projectId: 'socailmediaapp-f2758',
    storageBucket: 'socailmediaapp-f2758.firebasestorage.app',
    iosBundleId: 'com.example.socailMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5QaiFJdBxCrvQbyYA823znZZj68JPmYI',
    appId: '1:209148374373:ios:6e117850347ce93b97458c',
    messagingSenderId: '209148374373',
    projectId: 'socailmediaapp-f2758',
    storageBucket: 'socailmediaapp-f2758.firebasestorage.app',
    iosBundleId: 'com.example.socailMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAxsfjMA5Fj-n3JHsVpxpXhiExx4j6qNQ',
    appId: '1:209148374373:web:b9bcc919222b149297458c',
    messagingSenderId: '209148374373',
    projectId: 'socailmediaapp-f2758',
    authDomain: 'socailmediaapp-f2758.firebaseapp.com',
    storageBucket: 'socailmediaapp-f2758.firebasestorage.app',
    measurementId: 'G-68LQG378G9',
  );
}
